### ISSUE TITLE
RealmTableViewController is ignoring sectionNameKeyPath

### ISSUE THREAD

**Issue by skydivedan** [bigfish24/ABFRealmTableViewController#5]
In updateFetchedResultsController, this line is bad:

`self.fetchedResultsController.updateFetchRequest(fetchRequest, sectionNameKeyPath: nil, andPeformFetch: true)
`

It's sending "nil" for sectionNameKeyPath, when we have a "sectionNameKeyPath" property. I created a PR for this here:  https://github.com/bigfish24/ABFRealmTableViewController/pull/3

**Comment by bigfish24** [comment]
Thanks for adding this PR!
