### ISSUE TITLE
I'd like to call "indexPathForObject", so I can pre-select an item in the table

### ISSUE THREAD

**Issue by skydivedan** [bigfish24/ABFRealmTableViewController#6]
RealmTableViewController has a property named "fetchedResultsController", which is a private instance of RBQFetchedResultsController. Normally this isn't problem... unless I want to highlight a cell, programmatically, based on an object which I know to be in the result-set. 

Essentially, I want to say `self.tableView.selectRowAtIndexPath(self.fetchedResultsController.indexPathForObject(objectInResults))`

where `objectInResults` is an object that I know to be a valid object that ends up getting displayed in this table.

Unfortunately, `fetchedResultsController` is private, so I can't do this. I know that selectRowAtIndexPath only redraws the cell, and doesn't trigger anything else. But that's all I really need. I just want to force the selection, based on a single object.

**Comment by bigfish24** [comment]
The fetched results controller should be public. I will fix!

**Comment by bigfish24** [comment]
Fixed https://github.com/bigfish24/ABFRealmTableViewController/releases/tag/v1.5.1
